fn_single_line = true
format_strings = true
group_imports = "StdExternalCrate"
match_block_trailing_comma = true
max_width = 100
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 20
wrap_comments = true
