[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
itertools = "0.10.5"
lazy_static = "1.4.0"
num = { version = "0.4.0", features = ["num-bigint"] }
regex = "1.7.0"
scan_fmt = "0.2.6"
